[package]
name = "storyforge-content"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
storyforge-core = { path = "../storyforge-core" }
thiserror.workspace = true

[lints]
workspace = true
