[workspace]
members = ["crates/*"]
resolver = "3"
default-members = ["crates/storyforge-tui"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
repository = "https://github.com/toonchavez8/82-Storyforge-TUI.git"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"

[workspace.lints.rust]
future_incompatible = { level = "warn", priority = -1 }
missing_docs = "warn"
nonstandard_style = { level = "deny", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
redundant_clone = "deny"
large_enum_variant = "warn"
needless_collect = "warn"
