[package]
name = "storyforge-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
storyforge-content = { path = "../storyforge-content" }
storyforge-core = { path = "../storyforge-core" }

[lints]
workspace = true
