[package]
name = "storyforge-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.2"
storyforge-content = { path = "../storyforge-content" }
storyforge-core = { path = "../storyforge-core" }

[lints]
workspace = true
